export const orderAdminSelect = {
  id: true,
  orderNumber: true,
  status: true,
  paymentMethod: true,
  paymentStatus: true,
  customerName: true,
  customerPhone: true,
  customerEmail: true,
  deliveryStreet: true,
  deliveryZone: true,
  deliveryNotes: true,
  deliveryLatitude: true,
  deliveryLongitude: true,
  distanceKm: true,
  etaMinutes: true,
  deliveryFeeConsentAt: true,
  deliveryFeeConsentText: true,
  deliveryFeePolicyNearby: true,
  deliveryFeePolicyFarther: true,
  subtotal: true,
  deliveryFee: true,
  discountTotal: true,
  total: true,
  prepTargetMins: true,
  createdAt: true,
  updatedAt: true,
  items: { orderBy: { createdAt: "asc" }, select: { id: true, name: true, variantLabel: true, note: true, quantity: true, unitPrice: true, lineTotal: true } },
  timeline: { orderBy: { createdAt: "asc" }, select: { id: true, status: true, title: true, note: true, createdAt: true } },
};

export const orderDriverSelect = {
  id: true,
  orderNumber: true,
  status: true,
  customerName: true,
  customerPhone: true,
  deliveryStreet: true,
  deliveryZone: true,
  deliveryNotes: true,
  deliveryLatitude: true,
  deliveryLongitude: true,
  distanceKm: true,
  etaMinutes: true,
  createdAt: true,
  updatedAt: true,
  items: {
    orderBy: { createdAt: "asc" },
    select: { id: true, name: true, note: true, quantity: true },
  },
};

export function serializeAdminOrder(order) {
  return {
    id: order.id,
    orderNumber: order.orderNumber,
    status: order.status,
    paymentMethod: order.paymentMethod,
    paymentStatus: order.paymentStatus,
    customerName: order.customerName,
    customerPhone: order.customerPhone,
    customerEmail: order.customerEmail || "",
    deliveryStreet: order.deliveryStreet,
    deliveryZone: order.deliveryZone || "",
    deliveryNotes: order.deliveryNotes || "",
    deliveryLatitude: order.deliveryLatitude === null ? null : Number(order.deliveryLatitude),
    deliveryLongitude: order.deliveryLongitude === null ? null : Number(order.deliveryLongitude),
    distanceKm: order.distanceKm === null ? null : Number(order.distanceKm),
    etaMinutes: order.etaMinutes,
    deliveryFeeConsentAt: order.deliveryFeeConsentAt?.toISOString() || null,
    deliveryFeeConsentText: order.deliveryFeeConsentText || "",
    deliveryFeePolicyNearby: order.deliveryFeePolicyNearby === null ? null : Number(order.deliveryFeePolicyNearby),
    deliveryFeePolicyFarther: order.deliveryFeePolicyFarther === null ? null : Number(order.deliveryFeePolicyFarther),
    deliveryFeeConfirmed: Number(order.deliveryFee) > 0,
    subtotal: Number(order.subtotal),
    deliveryFee: Number(order.deliveryFee),
    discountTotal: Number(order.discountTotal),
    total: Number(order.total),
    prepTargetMins: order.prepTargetMins,
    createdAt: order.createdAt.toISOString(),
    updatedAt: order.updatedAt.toISOString(),
    items: order.items.map((item) => ({ ...item, unitPrice: Number(item.unitPrice), lineTotal: Number(item.lineTotal) })),
    timeline: order.timeline.map((event) => ({ ...event, createdAt: event.createdAt.toISOString() })),
  };
}

export function serializeDriverOrder(order) {
  return {
    id: order.id,
    orderNumber: order.orderNumber,
    status: order.status,
    customerName: order.customerName,
    customerPhone: order.customerPhone,
    deliveryStreet: order.deliveryStreet,
    deliveryZone: order.deliveryZone || "",
    deliveryNotes: order.deliveryNotes || "",
    deliveryLatitude: order.deliveryLatitude === null ? null : Number(order.deliveryLatitude),
    deliveryLongitude: order.deliveryLongitude === null ? null : Number(order.deliveryLongitude),
    distanceKm: order.distanceKm === null ? null : Number(order.distanceKm),
    etaMinutes: order.etaMinutes,
    createdAt: order.createdAt.toISOString(),
    updatedAt: order.updatedAt.toISOString(),
    items: order.items,
  };
}
