ALTER TABLE "StorefrontSettings"
ADD COLUMN IF NOT EXISTS "freeDeliveryEnabled" BOOLEAN NOT NULL DEFAULT false,
ADD COLUMN IF NOT EXISTS "freeDeliveryMaxKm" DECIMAL(8,2) NOT NULL DEFAULT 2.00,
ADD COLUMN IF NOT EXISTS "freeDeliveryMinimum" DECIMAL(10,2) NOT NULL DEFAULT 20.00;
