ALTER TABLE "MenuItem" DROP CONSTRAINT IF EXISTS "MenuItem_tagId_fkey";
DROP INDEX IF EXISTS "MenuItem_tagId_idx";
ALTER TABLE "MenuItem" DROP COLUMN IF EXISTS "tagId";
DROP TABLE IF EXISTS "MenuTag";
